### ISSUE TITLE
Can't get raw data of ICMP packet

### ISSUE THREAD

**Issue by Nazar01** [kaitoy/pcap4j#96] opened 2017-05-10 11:44 UTC
I'm trying to write my traceroute program, and I'm sending udp packets with 1 byte of payload,
but when I receive ICMP time exceeded packets I can see my payload only with 
`byte[] rawData = packet.getRawData()`
I want to use this
`byte[] rawData = packet.get(IcmpV4TimeExceededPacket.class).getPayload().getRawData();`
But it cuts all payload, I get only IP and UDP headers

**Comment by kaitoy** [comment] 2017-05-10 14:43
If you want get raw data of an ICMP packet you do:
`byte [] rawData = packet.get(IcmpV4CommonPacket.class).getRawData();`

**Comment by Nazar01** [comment] 2017-05-10 15:05
With this I don't get UDP payload(1 byte) too, your code just cuts some headers, but the byte is at the end of the packet

**Comment by Nazar01** [comment] 2017-05-10 15:10
`packet.getRawData()`
`080027B7FEB62E1BB7B83731080045C00039AA7800003D014837C0A80301C0A806030B00EF2A000000004500001D000000000111BFC0C0A806034A7DE8E7001500F5000900C204`

`packet.get(IcmpV4TimeExceededPacket.class).getPayload().getRawData()`
`4500001D000000000111BFC0C0A806034A7DE8E7001500F5000900C2`

`packet.get(IcmpV4CommonPacket.class).getRawData()`
`0B00EF2A000000004500001D000000000111BFC0C0A806034A7DE8E7001500F5000900C2`

**Comment by kaitoy** [comment] 2017-05-10 15:14
Why do you think the one byte should be at the end of the packet?
`packet.getRawData()` returns the raw data of the entire packet. If it doesn't include the one byte the packet doesn't include it.

**Comment by Nazar01** [comment] 2017-05-10 15:15
Because with `packet.getRawData()` I get it at the end of the packet

**Comment by kaitoy** [comment] 2017-05-10 15:20
Ah, now I understand the problem you reported. I will take a look at it.

**Comment by kaitoy** [comment] 2017-05-11 14:03
I couldn't reproduce it.
When I do `packet.get(IcmpV4TimeExceededPacket.class).getPayload().getRawData()`, it showed:
`4500001d000000000111bfc0c0a806034a7de8e7001500f5000900c204`

**Comment by kaitoy** [comment] 2017-05-13 03:04
I found the cause.
According to [RFC792](https://tools.ietf.org/html/rfc792), an ICMPv4 Time Exceeded Message should hold only "Internet Header + 64 bits of Original Data Datagram", but your UDP packet is 9 bytes, so Pcap4j trimmed last one byte (i.e. 0x04) and put it at the Ethernet trailer.
This behavior changed for #76 such that Pcap4J doesn't strictly comply with the RFC and lets a Time Exceeded Message hold any length of data. This change will be released in 1.7.1.

**Closed by kaitoy** 2017-05-13 03:04 UTC
