### ISSUE TITLE
How to work getNextPacket in case BlockingMode BLOCKING

### ISSUE THREAD

**Issue by MasaakiKoya** [kaitoy/pcap4j#206] opened 2019-02-22 08:20 UTC
Hi,
I tried packet capture, use to method getNextPacket(). However, it is not work. Occured IllegalMonitorStateException in notifyAll(). The bellow code is test code that  I tried. Is it wrong? Please suggest me correct way to use getNextPacket() in BLOCKING mode.

-------
import java.net.InetAddress;
import java.net.UnknownHostException;

import org.pcap4j.core.BpfProgram.BpfCompileMode;
import org.pcap4j.core.NotOpenException;
import org.pcap4j.core.PcapHandle;
import org.pcap4j.core.PcapNativeException;
import org.pcap4j.core.PcapNetworkInterface;
import org.pcap4j.core.PcapNetworkInterface.PromiscuousMode;
import org.pcap4j.core.Pcaps;
import org.pcap4j.packet.Packet;

public class GetNextPacketTest {

    private static final String COUNT_KEY = GetNextPacketTest.class.getName() + ".count";
    private static final int COUNT = Integer.getInteger(COUNT_KEY, 5);

    private static final String READ_TIMEOUT_KEY = GetNextPacketTest.class.getName() + ".readTimeout";
    private static final int READ_TIMEOUT = Integer.getInteger(READ_TIMEOUT_KEY, 10); // [ms]

    private static final String SNAPLEN_KEY = GetNextPacketTest.class.getName() + ".snaplen";
    private static final int SNAPLEN = Integer.getInteger(SNAPLEN_KEY, 65536); // [bytes]

    public static void main(String[] args) throws PcapNativeException, NotOpenException, UnknownHostException {

	System.out.println(COUNT_KEY + ": " + COUNT);
	System.out.println(READ_TIMEOUT_KEY + ": " + READ_TIMEOUT);
	System.out.println(SNAPLEN_KEY + ": " + SNAPLEN);
	System.out.println("\n");

	InetAddress address = InetAddress.getByName("127.0.0.1");
	String filter = "dst port 58888 and udp";

	PcapNetworkInterface nif = Pcaps.getDevByAddress(address);
	PcapHandle handle = nif.openLive(SNAPLEN, PromiscuousMode.PROMISCUOUS, READ_TIMEOUT);
	handle.setBlockingMode(PcapHandle.BlockingMode.BLOCKING);
	handle.setFilter(filter, BpfCompileMode.OPTIMIZE);

	Thread pThread = new Thread(new Capture(handle));
	Thread cThread = new Thread(new Stopper(handle));
	pThread.start();
	cThread.start();
    }
}

class Capture implements Runnable {

    private PcapHandle pcapHandle;

    public Capture(PcapHandle handle) {
	this.pcapHandle = handle;
    }

    public void run() {
	for (;;) {
	    try {
		Packet packet = pcapHandle.getNextPacket();
		if (null == packet) {
		    pcapHandle.close();
		    System.out.println("closed.");
		    break;
		}
		System.out.println(pcapHandle.getTimestamp());
		System.out.println(packet);

	    } catch (NotOpenException e) {
		e.printStackTrace();
	    }
	}
    }
}

class Stopper implements Runnable {

    private PcapHandle pcapHandle;

    public Stopper(PcapHandle handle) {
	this.pcapHandle = handle;
    }

    public void run() {
	int cnt = 0;
	for (int i = 0; i < 10; i++) {
	    try {
		Thread.sleep(1000);
		cnt++;
	    } catch (InterruptedException e) {
	    }
	    if (5 < cnt) {
		stop();
		break;
	    } else {
		System.out.println("cnt:" + cnt);
	    }
	}
    }

    synchronized public void stop() {
	System.out.println("call stop");
	this.pcapHandle.notifyAll();
    }
}

**Comment by kaitoy** [comment] 2019-02-24 14:01
`this.pcapHandle.notifyAll();`

It looks like here is the cause of the error because no thread is waiting on `this.pcapHandle` (i.e. No one calls `this.pcapHandle.wait()`).

**Comment by MasaakiKoya** [comment] 2019-02-25 02:23
My understanding was wrong. I thought I could force return from BLOCKING getNextPacket() by calling notifyAll(). (Just when, I did expected return null.)
Can not force return from BLOCKING getNextPacket() ?

**Comment by kaitoy** [comment] 2019-02-25 22:57
`pcapHandle.breakLoop()` might do what you want because `getNextPacket()` calls [pcap_dispatch()](https://linux.die.net/man/3/pcap_dispatch) internally.

**Comment by MasaakiKoya** [comment] 2019-02-26 03:21
kaitoy-san,
Thank you for your suggestion. I tried call breakLoop(). after few sec,  getNextPacket() returned null and return.

**Comment by kaitoy** [comment] 2019-02-26 13:46
That's good. I close this.

**Closed by kaitoy** 2019-02-26 13:46 UTC
